name: dynamic_logger
description: "A flexible, extensible, and customizable logging solution for Flutter applications that provides multiple logging targets, log levels, and formatting options."
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

